version: "3"
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.0
    container_name: zookeeper
    ports:
      - 2181:2181
      - 8080:8080
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      KAFKA_OPTS: "-javaagent:/jmx-reporter/jmx_prometheus_javaagent.jar=0.0.0.0:8080:/etc/prometheus-config/zookeeper.yml"
    volumes:
      - ./zookeeper/zookeeper.yml:/etc/prometheus-config/zookeeper.yml:ro
      - ./jmx-reporter:/jmx-reporter


  kafka:
    build: kafka/
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
      - 8079:8079
    environment:
      KAFKA_OPTS: "-javaagent:/jmx-reporter/jmx_prometheus_javaagent.jar=0.0.0.0:8079:/etc/prometheus-config/kafka.yml"
    volumes:
      - ./jmx-reporter:/jmx-reporter
      - ./kafka/prometheus/kafka.yml:/etc/prometheus-config/kafka.yml:ro

  grafana:
    image: grafana/grafana:6.4.1
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_INSTALL_PLUGINS: jdbranham-diagram-panel
  grafana-setup:
    build: grafana-setup/
    depends_on:
      - grafana
  slow-kafka-consumer:
    image: framiere/slow-kafka-consumer
    restart: on-failure
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      TOPIC: telegraf
      GROUP_ID: slow-consumer
    depends_on:
      - kafka

  kafka-producer:
    image: purbon/kafka-clients:latest
    container_name: kafka-producer
    ports:
     - 8078:8078
    environment:
       KAFKA_SERVERS: "kafka:9092"
       CLIENT_MODE: "producer"
    depends_on:
     - kafka

  kafka-consumer:
    image: purbon/kafka-clients:latest
    container_name: kafka-consumer
    ports:
     - 8077:8077
    environment:
     KAFKA_SERVERS: "kafka:9092"
     CLIENT_MODE: "consumer"
    depends_on:
     - kafka

  kafka-streams-app:
      image: purbon/kafka-streams-app:latest
      container_name: kafka-streams-app
      ports:
       - 8099:8099
      environment:
       KAFKA_SERVERS: "kafka:9092"
      depends_on:
       - kafka

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
